### PR TITLE
Fix stream :halt handling

### PR DESCRIPTION
**Pull request by awetzel**
Hello again Frank, there is an improvement/fix to make to the stream feature, to handle the ":halt" of the underlying enumerable, because when it is a "resource" stream, the :halt triggers the function to free the resource (close the tcp stream, close the file handler, etc.). The API does not change it is just a fix, so maybe a minor update would be sufficient.

I tried to respect your coding convention this time.

- :halt while parsing is running, wait next continuation in order to :
  - flush and ignore all emitted elements after halt
  - call {:halt,acc} continuation to halt the underlying stream
- end of xml document must call :halt to the underlying stream, since
  more bytes can be available

Tests are completed:

- random data has been added after the simple_stream.xml
- number of opened port is monitored to see if the stream is closed or
  not and test the above use cases

### CODE REVIEW

**Comment by gniquil** [comment]
@awetzel Hey, I just merged your change and update hex.pm. 

Anyway, I'd like to know if it's possible for you to take over the project. I have been doing much more Clojure lately rather than Elixir. I don't think I am doing justice to this project. And you are probably the most qualified among all the contributors. Let me know. (I am not sure how this will work yet, but if you are ok, I will look up how to transfer the project to you).

**Comment by awetzel** [comment]
@gniquil thank you very much for the merge.

I am doing more and more Elixir in my company so I think I could maintain this project if you cannot do it anymore. I do not know exactly how you can transfer the project since I have never did such a thing. I am not sure how to do that in hex.pm.

**Comment by gniquil** [comment]
@awetzel I just checked github. In order for me to transfer the ownership to you, could you delete your fork of sweet_xml?

**Comment by awetzel** [comment]
@gniquil Done

**Comment by awetzel** [comment]
@gniquil Hello Frank, can you add me as owner on hex.pm for sweet xml in order to allow me to update the project ? my email on hex is : "arnaudDOTwetzelATgmail". You can use the mix task "mix hex.owner add sweet_xml MYMAIL" to add me. Thank you very much.

**Comment by gniquil** [comment]
Hi Arnald,

DONE!

—
Frank

**Comment by awetzel** [comment]
Thank you very much it works !  Have a nice day.

**Pull request merged**
